### ISSUE TITLE
Remove billing plans when terminating an offer

### ISSUE THREAD

**Issue by farinalvaro** [rsksmart/rif-marketplace-storage#141]
## Steps to reproduce
- As a provider, set an offer with a billing plan `A`
- Terminate that offer
- Create another offer with billing plan `B` (different period and/or currency than `A`)

## Expected behavior
- To have an offer with billing plan `B`

## Actual behavior
- The offer contains billing plan `A` and billing plan `B`

**Comment by AuHau** [comment]
Hmm on second thought I don't think we can solve this in the contract.

The Billing Plans are mapping to an Offer, to my knowledge you can't iterate over mappings in Solidity, so we have to solve it somewhere else.

**Comment by julianmrodri** [comment]
So we will need to handle this in the UI when sending the TX. Should we close the issue what do you think @nduchak ?

**Comment by nduchak** [comment]
Yes, looks like we can
