### ISSUE TITLE
Accept RIF Token payments (in addition to RBTC)

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-storage#27]
Adapt the Smart Contract to be able to set the price in RIF (ERC 677) or RBTC. Also the user/consumer should be able to pay in the corresponding currency depending on whats set in the offer (RIF or RBTC).

Note: In the future will need to be extended to other payment methods such as ERC20 or ERC777 tokens.

**Comment by AuHau** [comment]
We are currently awaiting until all other changes will be implemented, then we will revisit this one.

**Comment by julianmrodri** [comment]
I dont think this is blocked anymore. i will remove the label.

**Comment by julianmrodri** [comment]
CLosed with latest changes.
